### ISSUE TITLE
🛠 Update issue template of publish

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/.github#28]
## Overview

* 

## Tasks

- [x] Remove unnecessary period in tasks
- [x] Write about checking `npm whoami --registry https://npm.pkg.github.com` before publish
- [x] Remove `- [ ]` from procedure of login
