### ISSUE TITLE
💪 Add Node and npm version into `publish` issue template

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/.github#30]
## Overview

* Add node and npm version into `publish` issue template

## Tasks

- [x] Add template of Node version
- [x] Add template of npm version
- [x] Add `git status` before `npm publish`
- [x] Add confirmation commands before `npm publish`
