### ISSUE TITLE
💪 Update `publish.md` issue template

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/.github#46]
# Tasks

- [x] Add `git fetch origin --prune` before `git log --graph --oneline --decorate --all` in `publish.md` of issue template
- [x] ~Add `vvvvvvv` after `pacakge.json` and `package-lock.json`~
- [x] Add `Inherit access from source repository (recommended)` in `4. Confirm Access Right of Published Package`
